/* Canoe and kayak (sprint and slalom). Rules follow the ICF. */
(function(){
const svg = `<svg viewBox="0 0 800 340" role="img" aria-label="A canoe slalom course"><rect width="800" height="340" fill="#2F7546"/>
  <path d="M0 60Q200 120 400 90T800 150V300Q600 250 400 280T0 230Z" fill="#3C8DC4"/>${[[120,120],[300,170],[500,140],[660,200]].map(([x,y]) => `<path d="M${x-30} ${y}q10 -8 20 0t20 0" fill="none" stroke="#fff" stroke-width="2"/>`).join("")}
  ${[[150,140,"g"],[250,190,"r"],[360,150,"g"],[470,215,"r"],[580,170,"g"],[690,220,"g"]].map(([x,y,c]) => `<line x1="${x - 20}" y1="${y - 40}" x2="${x - 20}" y2="${y + 4}" stroke="${c === "g" ? "#2FBF5A" : "#D9342B"}" stroke-width="6"/><line x1="${x + 20}" y1="${y - 40}" x2="${x + 20}" y2="${y + 4}" stroke="${c === "g" ? "#2FBF5A" : "#D9342B"}" stroke-width="6"/><line x1="${x - 24}" y1="${y - 40}" x2="${x + 24}" y2="${y - 40}" stroke="#18221D" stroke-width="2"/>`).join("")}
  <text x="30" y="40" font-family="Barlow,sans-serif" font-size="13" fill="#fff">Start (upstream)</text><text x="770" y="320" text-anchor="end" font-family="Barlow,sans-serif" font-size="13" fill="#fff">Finish</text><path d="M60 70l40 10" stroke="#fff" stroke-width="3"/>
  <rect class="hz" data-zone="green" x="125" y="95" width="50" height="55"/><rect class="hz" data-zone="green" x="335" y="105" width="50" height="55"/><rect class="hz" data-zone="green" x="555" y="125" width="50" height="55"/><rect class="hz" data-zone="green" x="665" y="175" width="50" height="55"/>
  <rect class="hz" data-zone="red" x="225" y="145" width="50" height="55"/><rect class="hz" data-zone="red" x="445" y="170" width="50" height="55"/>
  <rect class="hz" data-zone="water" x="40" y="230" width="300" height="40"/><rect class="hz" data-zone="start" x="20" y="24" width="120" height="40"/><rect class="hz" data-zone="finish" x="680" y="300" width="110" height="30"/></svg>`;
const ZONES = {
  green:{title:"Green gates", text:"Pass through these going downstream, with the current."},
  red:{title:"Red gates", text:"Pass through these going upstream, against the current, so paddlers must turn around behind them. They're the hardest gates."},
  water:{title:"Whitewater", text:"An artificial or natural river channel with rapids, eddies, and waves."},
  start:{title:"Start", text:"Paddlers start one at a time at the top of the course and race the clock."},
  finish:{title:"Finish", text:"Time stops when the paddler's body crosses the finish line. Penalties are added to the time."}
};
function slalom(){
  const $ = id => document.getElementById(id);
  function draw(){
    const t = +$("ckT").value, tc = +$("ckTouch").value, ms = +$("ckMiss").value, total = t + tc*2 + ms*50;
    $("ckTv").textContent = `${t.toFixed(1)} s`; $("ckTcv").textContent = tc; $("ckMsv").textContent = ms;
    $("ckOut").innerHTML = `<div class="scorebar"><div><small>Run time</small><b>${t.toFixed(2)}</b></div><span>+</span><div><small>Touches x 2 s</small><b>${tc*2}</b></div><span>+</span><div><small>Missed gates x 50 s</small><b>${ms*50}</b></div><span>=</span><div class="tot"><small>Final time</small><b>${total.toFixed(2)}</b></div></div>`;
    $("ckMsg").textContent = ms ? "A missed gate costs 50 seconds: almost always the end of any medal hopes." : tc ? `Each gate touch adds 2 seconds. ${tc > 1 ? "A clean run could have been a lot faster." : ""}` : "A clean run with no penalties. Now it's all about raw speed.";
  }
  ["ckT","ckTouch","ckMiss"].forEach(id => $(id).addEventListener("input", draw)); draw();
}
SPORT_PAGES["canoe-kayak"] = {render: app => sportPage(app, {id:"canoe-kayak", p:"ck", name:"Canoe and kayak", alt:"The tabby cat paddling a yellow kayak with a double-bladed paddle",
  lede:"Paddle sports come in two main kinds. In sprint, boats race side by side in lanes on flat water. In slalom, paddlers race the clock down a whitewater course through hanging gates, with time penalties for touching or missing them. Kayakers sit and use a two-bladed paddle; canoeists kneel and use a single blade.",
  facts:[["2","seconds added for touching a gate"],["50","seconds added for missing one"],["200","to 1,000 m sprint races"],["9","lanes in a sprint race"]],
  diagram:{title:"A slalom course", svg, zones:ZONES, order:["green","red","water","start","finish"], first:"red"},
  blocks:[{id:"pen", title:"Work out a slalom time", lede:"Set the run time and penalties to see the final result.", html:`<div class="pbform"><label>Run time <span id="ckTv"></span><input id="ckT" type="range" min="85" max="110" step="0.1" value="92"></label><label>Gate touches <span id="ckTcv"></span><input id="ckTouch" type="range" min="0" max="5" step="1" value="1"></label><label>Missed gates <span id="ckMsv"></span><input id="ckMiss" type="range" min="0" max="2" step="1" value="0"></label></div><div id="ckOut"></div><div class="result narrator" style="margin-top:12px" aria-live="polite"><img src="${img("head.webp")}" alt=""><p id="ckMsg"></p></div>`, init:slalom},
    {id:"types", title:"Boats and events", html: cards([{big:"K", name:"Kayak", text:"Seated, legs forward, with a paddle that has a blade at each end."},{big:"C", name:"Canoe", text:"Kneeling, with a single-bladed paddle, switching sides or steering with each stroke."},{big:"Sprint", name:"Sprint", text:"Flat water, nine lanes, 200 m to 1,000 m. First to the line wins."},{big:"Slalom", name:"Slalom", text:"Whitewater, 18 to 25 gates, one paddler at a time against the clock."},{big:"Cross", name:"Kayak cross", text:"Four paddlers race down the slalom course together, with a ramp start and contact allowed."}])}],
  tricky:[["What counts as a touch?","Any contact between the paddler, paddle, or boat and a gate pole. Judges at each gate watch closely."],["What counts as a missed gate?","Not passing through it, going through it the wrong direction, or going through upside down. Each costs 50 seconds."],["Why are numbers like K1 and C2?","The letter is the boat type and the number is how many paddlers. K4 is a four-person kayak."],["Can you roll and keep going?","Yes. Paddlers often roll back up after capsizing, but leaving the boat ends the run."]],
  words:[["K1, K2, K4","Kayaks with 1, 2, or 4 paddlers."],["C1, C2","Canoes with 1 or 2 paddlers."],["Eddy","Calm water behind a rock where the current circles back."],["Eskimo roll","Rolling a capsized boat upright again."],["Upstream gate","A red gate."],["Penalty","Seconds added for gate faults."]],
  quiz:[{q:"How many seconds for touching a slalom gate?",o:["1","2","5","50"],a:1,why:"Two seconds."},{q:"How many seconds for missing a gate?",o:["10","20","50","100"],a:2,why:"Fifty seconds."},{q:"Which gates are paddled upstream?",o:["Green","Red","Yellow","All of them"],a:1,why:"Red gates."},{q:"How does a kayaker sit?",o:["Kneeling","Seated with legs forward","Standing","Lying down"],a:1,why:"Seated."},{q:"What paddle does a canoeist use?",o:["Double-bladed","Single-bladed","None","Two paddles"],a:1,why:"Single-bladed."},{q:"What does K2 mean?",o:["A two-person kayak","A second-round race","Kayak lane 2","A 2 km race"],a:0,why:"Two paddlers in a kayak."},{q:"In sprint, how do you win?",o:["Fewest penalties","First across the line","Judges' scores","Most gates"],a:1,why:"First to the line."},{q:"A run takes 90 s with 1 touch and no misses. What's the final time?",o:["90","91","92","140"],a:2,why:"90 + 2 = 92 seconds."},{q:"What's kayak cross?",o:["A sprint race","Four paddlers racing down a slalom course together","A rowing event","A relay"],a:1,why:"Head-to-head racing."},{q:"How many lanes in a sprint final?",o:["6","8","9","12"],a:2,why:"Nine."}],
  footer:"Rules on this page follow the ICF for canoe sprint and canoe slalom, used at the Olympics."})};
})();
