/* High jump. Rules follow World Athletics. */
(function(){
const svg = `<svg viewBox="0 0 700 300" role="img" aria-label="High jump area"><rect width="700" height="300" fill="#2B3831"/><rect x="0" y="250" width="700" height="50" fill="#C4553F"/>
  <rect x="380" y="190" width="260" height="60" rx="8" fill="#2F6FD6"/><line x1="370" y1="250" x2="370" y2="80" stroke="#ccc" stroke-width="6"/><line x1="650" y1="250" x2="650" y2="80" stroke="#ccc" stroke-width="6"/>
  <line x1="370" y1="120" x2="650" y2="120" stroke="#F2C230" stroke-width="5"/><path d="M60 250Q240 250 330 236" fill="none" stroke="#fff" stroke-width="2" stroke-dasharray="7 6"/><circle cx="330" cy="236" r="6" fill="#fff"/>
  <path d="M330 236Q420 40 520 160" fill="none" stroke="#7FD39A" stroke-width="3" stroke-dasharray="8 6"/>
  <rect class="hz" data-zone="bar" x="370" y="110" width="280" height="20"/><rect class="hz" data-zone="uprights" x="360" y="80" width="20" height="170"/><rect class="hz" data-zone="uprights" x="640" y="80" width="20" height="170"/>
  <rect class="hz" data-zone="mat" x="382" y="190" width="256" height="60"/><rect class="hz" data-zone="runup" x="40" y="236" width="270" height="30"/><circle class="hz" data-zone="takeoff" cx="330" cy="236" r="16"/></svg>`;
const ZONES = {
  bar:{title:"The crossbar", text:"A light bar resting on small supports. If it falls, the jump is a failure, even if the jumper went over."},
  uprights:{title:"Uprights", text:"The two stands that hold the bar. The bar is raised after each round."},
  mat:{title:"Landing mat", text:"A thick foam mat, needed because jumpers land on their back and shoulders."},
  runup:{title:"Run-up", text:"A curved run of about 10 steps, letting the jumper lean away from the bar before takeoff."},
  takeoff:{title:"Takeoff", text:"The jumper must take off from one foot. Two-footed takeoffs aren't allowed."}
};
const game = attemptsGame("hjG", [2.14,2.18,2.22,2.26,2.29,2.32,2.35,2.38], "m", [{n:"Rival A", s:2.31},{n:"Rival B", s:2.28},{n:"Rival C", s:2.25}], 2.29);
SPORT_PAGES["high-jump"] = {render: app => sportPage(app, {id:"high-jump", p:"hj", name:"High jump", alt:"The tabby cat arching backward over a high jump bar",
  lede:"Jumpers try to clear a bar without knocking it off, taking off from one foot. The bar goes up after each round. Every athlete gets three tries at each height, and three misses in a row means you're out. The highest clearance wins.",
  facts:[["3","attempts per height"],["1","foot takeoff"],["2.45","meters: the men's world record"],["0","times you may knock the bar off"]],
  diagram:{title:"The jumping area", svg, zones:ZONES, order:["bar","uprights","mat","runup","takeoff"], first:"bar", max:700},
  blocks:[{id:"game", title:"Compete in a final", lede:"Jump or pass at each height. O is a clearance, X a miss, and a dash a pass. Watch countback decide ties.", html:game.html, init:game.init},
    {id:"rules", title:"Key rules", html: cards([{big:"3", name:"Three misses and out", text:"Three failures in a row, at any heights, end your competition."},{big:"Pass", name:"Passing", text:"You can skip heights to save energy, but misses already taken still count toward three in a row."},{big:"Countback", name:"Ties", text:"Ties go to whoever had fewer misses at the last height cleared, then fewer misses overall. A tie for first can go to a jump-off."},{big:"1 foot", name:"One-foot takeoff", text:"Every jump must take off from one foot."}])}],
  tricky:[["Why do jumpers go over backward?","The Fosbury Flop, first used at the 1968 Olympics, lets the body arch over the bar while the center of mass stays below it."],["Why pass a height?","Each jump costs energy. A confident jumper may skip lower heights to save their legs for the bigger ones."],["Is touching the bar a miss?","No. The bar can wobble; it's only a failure if it falls off."],["Can two jumpers share gold?","Yes, if they agree after a tie that countback can't break. It happened at the 2020 Olympics men's high jump."]],
  words:[["Fosbury Flop","The backward, head-first technique all top jumpers use."],["Clearance","A successful jump."],["Countback","The tiebreaking rules."],["Jump-off","An extra round to decide first place."],["Approach","The run-up."],["Personal best","An athlete's highest-ever clearance."]],
  quiz:[{q:"How many attempts per height?",o:["1","2","3","Unlimited"],a:2,why:"Three."},{q:"How many misses in a row end your competition?",o:["2","3","4","5"],a:1,why:"Three."},{q:"What takeoff is required?",o:["Two feet","One foot","A run of 20 steps","A standing jump"],a:1,why:"One foot."},{q:"The bar wobbles but stays up. Is it a clearance?",o:["Yes","No"],a:0,why:"Yes, as long as it stays on."},{q:"Can you skip a height?",o:["Yes","No"],a:0,why:"Yes, you may pass."},{q:"How are ties broken?",o:["Coin toss","Fewer misses at the last height, then overall","Height of the athlete","Fastest run-up"],a:1,why:"Countback."},{q:"What's the Fosbury Flop?",o:["A failed jump","The backward head-first technique","A type of bar","A penalty"],a:1,why:"The modern technique."},{q:"Can two athletes share gold?",o:["Never","Yes, if they agree after an unbroken tie"],a:1,why:"It happened in 2021 (the Tokyo 2020 Games)."},{q:"What does 'XO' mean on a results sheet?",o:["Missed, then cleared","Cleared, then missed","Passed","Two misses"],a:0,why:"A miss, then a clearance."},{q:"What happens if the bar falls?",o:["It's still a clearance","It's a failure","The jump is replayed","Half points"],a:1,why:"A failure."}],
  footer:"Rules on this page follow World Athletics."})};
})();
