/* Lacrosse (men's field lacrosse, with notes on women's and sixes). Rules follow World Lacrosse; college details noted. */
(function(){
const W="#F4F6F1";
const svg = `<svg viewBox="-30 -30 830 480" role="img" aria-label="Men's lacrosse field from above"><rect x="-30" y="-30" width="830" height="480" fill="#1C4D2C"/><rect width="770" height="420" fill="#2F7546"/>
  <g stroke="${W}" stroke-width="3" fill="none"><rect width="770" height="420"/><line x1="385" y1="0" x2="385" y2="420"/><line x1="245" y1="0" x2="245" y2="420"/><line x1="525" y1="0" x2="525" y2="420"/>
  <line x1="0" y1="70" x2="245" y2="70"/><line x1="0" y1="350" x2="245" y2="350"/><line x1="525" y1="70" x2="770" y2="70"/><line x1="525" y1="350" x2="770" y2="350"/>
  <circle cx="105" cy="210" r="21"/><circle cx="665" cy="210" r="21"/><line x1="385" y1="60" x2="385" y2="80" stroke-width="6"/><line x1="385" y1="340" x2="385" y2="360" stroke-width="6"/></g>
  <path d="M100 200l10 0 0 20-10 0" fill="none" stroke="#D9342B" stroke-width="4"/><path d="M670 200l-10 0 0 20 10 0" fill="none" stroke="#D9342B" stroke-width="4"/><circle cx="385" cy="210" r="5" fill="#fff"/>
  <rect class="hz" data-zone="box" x="8" y="74" width="234" height="272"/><rect class="hz" data-zone="box" x="528" y="74" width="234" height="272"/>
  <circle class="hz" data-zone="crease" cx="105" cy="210" r="23"/><circle class="hz" data-zone="crease" cx="665" cy="210" r="23"/>
  <rect class="hz" data-zone="behind" x="8" y="180" width="70" height="60"/><rect class="hz" data-zone="behind" x="692" y="180" width="70" height="60"/>
  <rect class="hz" data-zone="mid" x="377" y="90" width="16" height="240"/><circle class="hz" data-zone="faceoff" cx="385" cy="210" r="14"/>
  <rect class="hz" data-zone="wings" x="377" y="40" width="16" height="44"/><rect class="hz" data-zone="wings" x="377" y="336" width="16" height="44"/>
  <rect class="hz" data-zone="restrain" x="237" y="0" width="16" height="420"/><rect class="hz" data-zone="restrain" x="517" y="0" width="16" height="420"/></svg>`;
const ZONES = {
  crease:{title:"The crease", text:"The circle around the goal. Attackers may not step into it, and a goal scored with a foot in the crease doesn't count. Inside it, the goalkeeper can't be checked."},
  behind:{title:"Behind the goal", text:"Unlike soccer, play continues behind the net. Attackers often set up there, called X, to pass to cutters."},
  box:{title:"Attack box", text:"The area between the restraining line and the end line. Many penalties and restarts relate to it."},
  restrain:{title:"Restraining lines", text:"Part of the offside rule: a team must keep at least four players (including the goalie) in its defensive half and three in its attacking half."},
  mid:{title:"Midfield line", text:"Splits the field. Midfielders are the only players who usually cross it freely."},
  faceoff:{title:"Faceoff spot", text:"Every quarter, and every goal, restarts with a faceoff: two players crouch over the ball and fight for it with their sticks."},
  wings:{title:"Wing lines", text:"During a faceoff, one midfielder from each team waits on each wing line, ready to sprint for the ball."}
};
const judge = scenarioJudge("lxJ", [
  {t:"An attacker scores while his foot is touching the crease line.", o:["Goal","No goal"], a:1, w:"The crease line is part of the crease. A shooter in the crease means no goal."},
  {t:"A shot misses the goal and goes out of bounds behind the net.", o:["Defense's ball","Ball to the player closest to where it went out"], a:1, w:"On a missed shot, possession goes to the player nearest the ball when it goes out, which is why attackers chase misses hard."},
  {t:"A defender slashes an attacker's arm with his stick.", o:["Play on","Personal foul: time in the penalty box"], a:1, w:"Slashing is a personal foul, usually 1 to 3 minutes. The other team plays man-up."},
  {t:"A team has only three players in its defensive half.", o:["Legal","Offside"], a:1, w:"Teams must keep four in the defensive half (including the goalie) and three in the attacking half."},
  {t:"A player picks up a ground ball with his hand.", o:["Legal","Illegal"], a:1, w:"Only the goalkeeper in the crease may touch the ball with the hand. Everyone else uses the stick."}
]);
SPORT_PAGES["lacrosse"] = {render: app => sportPage(app, {id:"lacrosse", p:"lx", name:"Lacrosse", alt:"The tabby cat in a lacrosse helmet and gloves, cradling the ball in a netted stick",
  lede:"Players use sticks with a small net, called a pocket, to catch, carry, and throw a hard rubber ball, trying to shoot it into the other team's goal. It's fast and physical, with checks allowed in the men's game, and play continues even behind the goals.",
  facts:[["10","players per side (men's field)"],["4","quarters"],["6","feet: the goal is 6 x 6"],["2028","returns to the Olympics as Sixes"]],
  diagram:{title:"The field", svg, zones:ZONES, order:["crease","behind","box","restrain","mid","faceoff","wings"], first:"crease"},
  blocks:[{id:"judge", title:"Make the call", html:judge.html, init:judge.init},
    {id:"forms", title:"Three kinds of lacrosse", html: cards([{big:"10", name:"Men's field lacrosse", text:"Ten players: three attackers, three midfielders, three defenders, and a goalie. Body checks and stick checks are allowed."},{big:"12", name:"Women's lacrosse", text:"Twelve players, much less contact, no body checking, and deeper rules about space around the goal."},{big:"6", name:"Sixes", text:"The Olympic format for 2028: six players a side on a small field, with quick 8-minute quarters and a short shot clock."}])},
    {id:"pen", title:"Penalties", html: cards([{big:"30 s", name:"Technical foul", text:"Holding, pushing, offside, or interfering. A short stay in the penalty box, or loss of possession."},{big:"1-3 min", name:"Personal foul", text:"Slashing, illegal body checks, cross-checking, or tripping. The team plays a player down."},{big:"Man-up", name:"Extra-man offense", text:"While an opponent is in the box, the attack has a player advantage, much like a hockey power play."}])}],
  clock:{segs:[{k:"q", cls:"q", t:"Quarters", s:"4", info:["Four quarters","Field lacrosse is played in four quarters, with a faceoff to start each one and after every goal."]},{k:"sc", cls:"half", t:"Shot clock", s:"Possession", info:["Shot clock","Teams must shoot on goal within the shot clock, 80 seconds in college field lacrosse."]},{k:"ot", cls:"ot", t:"Overtime", s:"Sudden death", info:["Overtime","Ties go to sudden-death overtime: next goal wins."]}]},
  tricky:[["Why do players cradle the stick?","Rocking the stick keeps the ball in the pocket while running, using a bit of centrifugal force."],["Can you hit the goalie?","Not in the crease. The goalie is protected there."],["Why is there a long stick?","Up to four players per team may use a long pole (up to 6 feet), mostly defenders, to poke and check."],["Is lacrosse an Olympic sport?","It was in 1904 and 1908, and returns in 2028 in the Sixes format."]],
  words:[["Cradle","Rocking the stick to keep the ball in the pocket."],["Pocket","The netting in the stick head."],["Faceoff","The battle for the ball to restart play."],["Ground ball","A loose ball scooped off the ground."],["Long pole","A defender's long stick."],["Crease","The circle around the goal."],["Man-up","Playing with an extra player after a penalty."],["X","The spot behind the goal."]],
  quiz:[{q:"How many players per side in men's field lacrosse?",o:["6","10","11","12"],a:1,why:"Ten."},{q:"Can attackers step into the crease?",o:["Yes","No"],a:1,why:"The crease belongs to the defense."},{q:"What restarts play after a goal?",o:["A throw-in","A faceoff","A goal kick","A drop ball"],a:1,why:"A faceoff."},{q:"A shot goes out of bounds. Who gets the ball?",o:["The defense","The player closest to the ball when it went out","The shooter's team always","The goalie"],a:1,why:"The closest player."},{q:"Can play happen behind the goal?",o:["Yes","No"],a:0,why:"Yes, the area behind the goal is in play."},{q:"How many must stay in the defensive half?",o:["2","3","4","6"],a:2,why:"Four, including the goalie."},{q:"What's a personal foul penalty?",o:["Loss of a goal","1 to 3 minutes in the box","Ejection always","A free shot"],a:1,why:"1 to 3 minutes."},{q:"Who may touch the ball with the hand?",o:["Anyone","The goalie in the crease","Defenders","Nobody"],a:1,why:"Only the goalie in the crease."},{q:"What's the Olympic format for 2028?",o:["Box lacrosse","Sixes","Field lacrosse","Women's only"],a:1,why:"Sixes."},{q:"What does 'cradle' mean?",o:["A defensive foul","Rocking the stick to keep the ball in","A type of shot","The goalie's save"],a:1,why:"Keeping control while running."}],
  footer:"Rules on this page follow men's field lacrosse under World Lacrosse, with college details noted. Women's lacrosse and box lacrosse have their own rules."})};
})();
