/* Pickleball. Rules follow the USA Pickleball rulebook (doubles, side-out scoring). */
(function(){
const svg = `<svg viewBox="-40 -40 960 520" role="img" aria-label="Pickleball court from above"><rect x="-40" y="-40" width="960" height="520" fill="#1C4D2C"/><rect width="880" height="440" fill="#2F6FD6"/>
  <rect x="300" y="0" width="280" height="440" fill="#7FB0E8"/><g stroke="#fff" stroke-width="5" fill="none"><rect width="880" height="440"/><line x1="300" y1="0" x2="300" y2="440"/><line x1="580" y1="0" x2="580" y2="440"/><line x1="0" y1="220" x2="300" y2="220"/><line x1="580" y1="220" x2="880" y2="220"/></g>
  <line x1="440" y1="-20" x2="440" y2="460" stroke="#18221D" stroke-width="8"/>
  <text x="440" y="-18" text-anchor="middle" font-family="Barlow,sans-serif" font-size="14" fill="#EEF3EC">Net</text><text x="370" y="232" text-anchor="middle" font-family="Barlow Condensed,sans-serif" font-weight="700" font-size="20" fill="#18221D">Kitchen</text><text x="510" y="232" text-anchor="middle" font-family="Barlow Condensed,sans-serif" font-weight="700" font-size="20" fill="#18221D">Kitchen</text>
  <rect class="hz" data-zone="kitchen" x="306" y="6" width="128" height="428"/><rect class="hz" data-zone="kitchen" x="446" y="6" width="128" height="428"/>
  <rect class="hz" data-zone="service" x="6" y="6" width="290" height="210"/><rect class="hz" data-zone="service" x="6" y="224" width="290" height="210"/><rect class="hz" data-zone="service" x="584" y="6" width="290" height="210"/><rect class="hz" data-zone="service" x="584" y="224" width="290" height="210"/>
  <rect class="hz" data-zone="net" x="432" y="-20" width="16" height="480"/><rect class="hz" data-zone="base" x="-38" y="0" width="40" height="440"/><rect class="hz" data-zone="base" x="878" y="0" width="40" height="440"/>
  <rect class="hz" data-zone="kline" x="292" y="0" width="16" height="440"/><rect class="hz" data-zone="kline" x="572" y="0" width="16" height="440"/></svg>`;
const ZONES = {
  kitchen:{title:"The kitchen (non-volley zone)", text:"The 7-foot zone on each side of the net. You can't hit the ball out of the air while standing in it, or touching its line. You can step in to hit a ball after it bounces."},
  kline:{title:"Kitchen line", text:"Part of the kitchen. Stepping on it during a volley is a fault, even on the follow-through."},
  service:{title:"Service courts", text:"The serve goes diagonally, into the opposite service court, and must clear the kitchen, landing beyond the kitchen line."},
  net:{title:"Net", text:"36 inches high at the sidelines and 34 inches in the middle."},
  base:{title:"Baseline", text:"Servers stand behind it. The court is 20 by 44 feet, the same size as a badminton doubles court."}
};
const judge = scenarioJudge("pbJ", [
  {t:"You volley the ball while your toe is on the kitchen line.", o:["Legal","Fault"], a:1, w:"The kitchen line is part of the kitchen. No volleys while touching it."},
  {t:"The returning team hits the serve back before it bounces.", o:["Legal","Fault"], a:1, w:"The two-bounce rule: the serve must bounce, and the return must bounce, before anyone volleys."},
  {t:"You step into the kitchen to hit a short ball after it bounced.", o:["Legal","Fault"], a:0, w:"Being in the kitchen is fine. Volleying in it is not."},
  {t:"The serve lands on the kitchen line.", o:["Good serve","Fault"], a:1, w:"A serve landing on the kitchen line is short, so it's a fault. Landing on other lines is good."},
  {t:"The receiving team wins the rally. Do they score a point?", o:["Yes","No, but they may win the serve"], a:1, w:"In traditional side-out scoring, only the serving team scores. Winning as the receiver earns the serve (or the second server's turn)."}
]);
SPORT_PAGES["pickleball"] = {render: app => sportPage(app, {id:"pickleball", p:"pb", name:"Pickleball", alt:"The tabby cat holding a pickleball paddle and a perforated ball",
  lede:"A mix of tennis, badminton, and table tennis, played with solid paddles and a plastic ball with holes on a small court. Serves are underhand, there's a no-volley zone near the net called the kitchen, and games usually go to 11.",
  facts:[["11","points a game, win by 2"],["7","feet: the kitchen on each side"],["2","bounces before volleys are allowed"],["3","numbers in a doubles score call"]],
  diagram:{title:"The court", svg, zones:ZONES, order:["kitchen","kline","service","net","base"], first:"kitchen"},
  blocks:[{id:"judge", title:"Make the call", html:judge.html, init:judge.init},
    {id:"score", title:"Reading the score", html: cards([{big:"4-2-1", name:"Three numbers", text:"In doubles the score is called as serving team's score, receiving team's score, then server number (1 or 2). 4-2-1 means the serving team has 4, the other team 2, and it's the first server."},{big:"Side-out", name:"Only servers score", text:"In traditional scoring, you only score while serving. Each partner serves until their team loses a rally, then the serve passes to the other team."},{big:"0-0-2", name:"The start", text:"The game starts at 0-0-2: only one partner serves at the start, so the first team doesn't get a big head start."}])}],
  clock:{segs:[{k:"g", cls:"q", t:"Game", s:"to 11", info:["Game","To 11, win by 2. Some tournaments play to 15 or 21."]},{k:"m", cls:"ot", t:"Match", s:"Best of 3", info:["Match","Tournaments often play best of three games."]}]},
  tricky:[["Why is it called the kitchen?","Nobody knows for sure. The official name is the non-volley zone."],["Why must the ball bounce twice?","The two-bounce rule stops the serving team from rushing the net and volleying the return, keeping rallies longer."],["What's a dink?","A soft shot from the kitchen line that drops into the opponent's kitchen. Dink rallies are where pickleball games are often won."],["Can you serve overhand?","No. The serve must be underhand, with contact below the waist."]],
  words:[["Kitchen","The non-volley zone."],["Dink","A soft shot into the kitchen."],["Erne","A jump around the side of the kitchen to volley near the net, legally."],["Side-out","Losing the serve to the other team."],["Third shot drop","A soft third shot that lets the serving team move up to the kitchen."],["Volley","Hitting the ball before it bounces."]],
  quiz:[{q:"What's the kitchen?",o:["The service area","The no-volley zone near the net","The bench","The baseline"],a:1,why:"The non-volley zone."},{q:"Can you volley while standing in the kitchen?",o:["Yes","No"],a:1,why:"No."},{q:"How must you serve?",o:["Overhand","Underhand, below the waist","Any way","Off a bounce only"],a:1,why:"Underhand."},{q:"What's the two-bounce rule?",o:["Every shot must bounce twice","The serve and return must each bounce before volleys","The ball may bounce twice","Two serves allowed"],a:1,why:"Serve and return bounce first."},{q:"How many points usually win a game?",o:["7","11","15","21"],a:1,why:"Eleven."},{q:"In side-out scoring, who can score?",o:["Either team","Only the serving team"],a:1,why:"Only the server."},{q:"What does 4-2-1 mean?",o:["4 games to 2","Server 4, receiver 2, first server","4 aces","Set 4"],a:1,why:"Three-number call."},{q:"A serve lands on the kitchen line. What's the call?",o:["Good","Fault"],a:1,why:"It's short."},{q:"Can you step into the kitchen to hit a bounced ball?",o:["Yes","No"],a:0,why:"Yes."},{q:"What's a dink?",o:["A hard smash","A soft drop into the kitchen","A foot fault","A lob"],a:1,why:"A soft shot."}],
  footer:"Rules on this page follow the USA Pickleball rulebook for doubles with traditional side-out scoring. Some events use rally scoring instead."})};
})();
