/* Pole vault. Rules follow World Athletics. */
(function(){
const svg = `<svg viewBox="0 0 760 320" role="img" aria-label="Pole vault area"><rect width="760" height="320" fill="#2B3831"/><rect x="0" y="270" width="760" height="50" fill="#C4553F"/>
  <rect x="470" y="210" width="270" height="60" rx="8" fill="#2F6FD6"/><path d="M440 270l20 0 -6 -18z" fill="#111"/><line x1="500" y1="270" x2="500" y2="40" stroke="#ccc" stroke-width="6"/><line x1="720" y1="270" x2="720" y2="40" stroke="#ccc" stroke-width="6"/>
  <line x1="500" y1="60" x2="720" y2="60" stroke="#F2C230" stroke-width="5"/><path d="M40 270H420" stroke="#fff" stroke-width="2" stroke-dasharray="8 6"/><path d="M455 262Q420 140 470 70" fill="none" stroke="#D7B98C" stroke-width="6"/>
  <rect class="hz" data-zone="bar" x="500" y="50" width="220" height="20"/><rect class="hz" data-zone="standards" x="490" y="40" width="20" height="230"/><rect class="hz" data-zone="standards" x="710" y="40" width="20" height="230"/>
  <rect class="hz" data-zone="box" x="432" y="250" width="36" height="24"/><rect class="hz" data-zone="mat" x="472" y="212" width="266" height="58"/><rect class="hz" data-zone="runway" x="30" y="260" width="390" height="22"/><rect class="hz" data-zone="pole" x="420" y="70" width="40" height="190"/></svg>`;
const ZONES = {
  runway:{title:"Runway", text:"At least 40 m long. Vaulters sprint with the pole held high, then lower it to plant."},
  box:{title:"Planting box", text:"A sunken box at the end of the runway. The pole's tip jams into it, and the pole bends."},
  pole:{title:"The pole", text:"A flexible fiberglass or carbon pole, chosen by each athlete for their weight and speed. It stores energy as it bends and flings the vaulter upward."},
  bar:{title:"Crossbar", text:"Like high jump, the bar must stay on. Clearing it while knocking it off is a failure."},
  standards:{title:"Standards", text:"The bar supports can be moved forward or back, so each vaulter sets where the bar sits relative to the box."},
  mat:{title:"Landing mat", text:"A huge, deep mat, because vaulters fall from over 6 meters."}
};
const game = attemptsGame("pvG", [5.60,5.70,5.80,5.87,5.94,6.00,6.05,6.10], "m", [{n:"Rival A", s:5.92},{n:"Rival B", s:5.86},{n:"Rival C", s:5.80}], 5.92);
SPORT_PAGES["pole-vault"] = {render: app => sportPage(app, {id:"pole-vault", p:"pv", name:"Pole vault", alt:"The tabby cat holding a long vaulting pole, ready to run",
  lede:"Vaulters sprint down a runway, plant a long flexible pole in a box, and ride its bend up and over a bar more than 6 meters high for top men. Like high jump, there are three attempts at each height and three misses in a row ends your day.",
  facts:[["6+","meters: elite men clear over 6 m"],["3","attempts per height"],["40","meters of runway at least"],["1","pole, bending almost in half"]],
  diagram:{title:"The vaulting area", svg, zones:ZONES, order:["runway","box","pole","bar","standards","mat"], first:"pole", max:760},
  blocks:[{id:"game", title:"Compete in a final", lede:"Same rules as high jump: jump or pass, three misses and out, and countback for ties.", html:game.html, init:game.init},
    {id:"rules", title:"Key rules", html: cards([{big:"3", name:"Three misses and out", text:"Three failures in a row end your competition."},{big:"Hands", name:"No moving hands up", text:"The upper hand can't move higher on the pole after takeoff."},{big:"Bar", name:"Bar must stay up", text:"Knocking the bar off, even with the pole, is a failure."},{big:"Time", name:"Time limit", text:"Vaulters have about a minute to start each attempt once called, less as the field shrinks."}])}],
  tricky:[["Can the pole break?","Rarely, but yes. A broken pole is replaced, and the athlete can retake the attempt."],["What if the pole knocks the bar off?","That's a failure, so vaulters push the pole back away from the bar as they let go."],["Why do vaulters carry several poles?","Different stiffness for different heights, wind, and how they feel that day."],["Why move the standards?","Moving the bar supports lets vaulters place the bar at the peak of their flight."]],
  words:[["Plant","Jamming the pole into the box."],["Swing up","Swinging the legs up as the pole bends."],["Inversion","Turning upside down at the top."],["Grip","How high the vaulter holds the pole."],["Standards","The bar supports."],["Box","Where the pole is planted."]],
  quiz:[{q:"How many attempts per height?",o:["1","2","3","5"],a:2,why:"Three."},{q:"What happens if the pole knocks the bar off?",o:["Clearance counts","It's a failure","Replay","Half points"],a:1,why:"A failure."},{q:"Where is the pole planted?",o:["In the mat","In the box","On the runway","Against the standards"],a:1,why:"In the box."},{q:"Can vaulters skip heights?",o:["Yes","No"],a:0,why:"Yes, they can pass."},{q:"What are poles made of?",o:["Wood","Steel","Fiberglass or carbon","Bamboo only"],a:2,why:"Flexible fiberglass or carbon fiber."},{q:"How high do elite men vault?",o:["About 4 m","About 5 m","Over 6 m","Over 8 m"],a:2,why:"Over 6 meters."},{q:"Can the upper hand slide up the pole after takeoff?",o:["Yes","No"],a:1,why:"Not allowed."},{q:"Three misses in a row means:",o:["A time penalty","You're out","You restart","Nothing"],a:1,why:"You're out."},{q:"Why do vaulters move the standards?",o:["To cheat","To place the bar at the peak of their flight","For decoration","To protect the mat"],a:1,why:"To fit their jump."},{q:"How are ties broken?",o:["Countback","Coin toss","Height of the pole","Judges' scores"],a:0,why:"Countback, as in high jump."}],
  footer:"Rules on this page follow World Athletics."})};
})();
