/* Squash. Rules follow World Squash, point-a-rally scoring to 11. */
(function(){
const svg = `<svg viewBox="0 0 860 420" role="img" aria-label="Squash front wall and court floor"><rect width="860" height="420" fill="#2B3831"/>
  <rect x="20" y="20" width="320" height="380" fill="#F4F2EC"/><line x1="20" y1="60" x2="340" y2="60" stroke="#D9342B" stroke-width="5"/><line x1="20" y1="230" x2="340" y2="230" stroke="#D9342B" stroke-width="4"/><rect x="20" y="370" width="320" height="30" fill="#C8B79A" stroke="#D9342B" stroke-width="4"/>
  <text x="180" y="414" text-anchor="middle" font-family="Barlow,sans-serif" font-size="13" fill="#EEF3EC">Front wall</text>
  <rect x="400" y="20" width="440" height="380" fill="#D7B98C"/><g stroke="#D9342B" stroke-width="4" fill="none"><rect x="400" y="20" width="440" height="380"/><line x1="400" y1="232" x2="840" y2="232"/><line x1="620" y1="232" x2="620" y2="400"/><rect x="400" y="232" width="70" height="70"/><rect x="770" y="232" width="70" height="70"/></g>
  <text x="620" y="414" text-anchor="middle" font-family="Barlow,sans-serif" font-size="13" fill="#EEF3EC">Floor seen from above (front wall at top)</text>
  <rect class="hz" data-zone="out" x="20" y="48" width="320" height="24"/><rect class="hz" data-zone="service" x="20" y="220" width="320" height="22"/><rect class="hz" data-zone="tin" x="20" y="366" width="320" height="34"/><rect class="hz" data-zone="wall" x="20" y="76" width="320" height="140"/>
  <rect class="hz" data-zone="short" x="400" y="222" width="440" height="20"/><rect class="hz" data-zone="boxes" x="400" y="244" width="70" height="58"/><rect class="hz" data-zone="boxes" x="770" y="244" width="70" height="58"/><rect class="hz" data-zone="half" x="610" y="244" width="20" height="156"/><rect class="hz" data-zone="t" x="595" y="210" width="50" height="40"/></svg>`;
const ZONES = {
  out:{title:"Out line", text:"The top line on the front wall (and running along the side walls). A ball hitting on or above it is out."},
  service:{title:"Service line", text:"The serve must hit the front wall above this line and below the out line."},
  tin:{title:"The tin", text:"The board at the bottom of the front wall. Hitting it, or below the line on top of it, loses the rally. It makes a loud metallic sound."},
  wall:{title:"Front wall", text:"Every shot must reach the front wall before bouncing twice, and can hit the side and back walls on the way."},
  short:{title:"Short line", text:"The serve must land behind this line, in the opposite back quarter of the court, unless the receiver volleys it."},
  boxes:{title:"Service boxes", text:"The server keeps at least one foot inside a service box, alternating boxes after each point won."},
  half:{title:"Half-court line", text:"Divides the back of the court for the serve."},
  t:{title:"The T", text:"Where the lines meet. Controlling the T lets a player reach every corner, so the best players return to it after every shot."}
};
const judge = scenarioJudge("sqJ", [
  {t:"You're about to hit a winning shot, but your opponent is standing in your path to the ball and you stop to avoid hitting them.", o:["Let","Stroke","No let"], a:1, w:"If the opponent's interference stopped a likely winning shot, or you would have hit them with a fair shot, it's a stroke: you win the point."},
  {t:"Your opponent is slightly in your way, but you could have reached the ball and played a good shot.", o:["Let","Stroke","No let"], a:0, w:"A let means the rally is replayed. You had a fair chance, but interference made it unfair to continue."},
  {t:"You stop and ask for a let, but you had no chance of reaching the ball anyway.", o:["Let","Stroke","No let"], a:2, w:"No let: you couldn't have got there, so your opponent wins the point."},
  {t:"Your shot clips the top of the tin.", o:["Good","Down: you lose the rally"], a:1, w:"Any ball touching the tin is down."},
  {t:"The score is 10-10.", o:["Next point wins","Play continues until someone leads by 2"], a:1, w:"Games go to 11, but you must win by 2."}
]);
SPORT_PAGES["squash"] = {render: app => sportPage(app, {id:"squash", p:"sq", name:"Squash", alt:"The tabby cat ready with a squash racket in a court",
  lede:"Two players share an enclosed court and take turns hitting a small rubber ball against the front wall. The ball can hit any wall on the way, but must reach the front wall before it bounces twice. Because players share the space, the rules about getting in each other's way matter as much as the scoring.",
  facts:[["11","points a game, win by 2"],["5","games at most, best of five"],["1","bounce allowed"],["2028","joins the Olympics"]],
  diagram:{title:"The court", svg, zones:ZONES, order:["wall","out","service","tin","short","boxes","half","t"], first:"tin"},
  blocks:[{id:"judge", title:"Let, stroke, or no let?", lede:"The referee's hardest calls. You decide.", html:judge.html, init:judge.init},
    {id:"rules", title:"Key rules", html: cards([{big:"Every rally", name:"Point-a-rally scoring", text:"Whoever wins a rally scores, whether or not they served."},{big:"Let", name:"Replay", text:"Interference made it unfair, but no winner was blocked."},{big:"Stroke", name:"Point awarded", text:"The opponent's interference stopped a winning shot or a fair swing."},{big:"Clear", name:"Get out of the way", text:"After hitting, a player must give the opponent a clear path to the ball and room to swing."}])}],
  clock:{segs:[{k:"g", cls:"q", t:"Games", s:"to 11", info:["Games","First to 11 points, win by 2."]},{k:"b", cls:"half", t:"Break", s:"90 s", info:["Between games","A short break of about 90 seconds."]},{k:"m", cls:"ot", t:"Match", s:"Best of 5", info:["Match","First to three games wins at top level."]}]},
  tricky:[["Why is it so tiring?","Rallies are long, the court is small, and players sprint and stop constantly. Matches can last over an hour."],["Why do players warm the ball?","Squash balls are hollow rubber and barely bounce when cold. Players hit them for a few minutes to warm them up."],["What do the dots on the ball mean?","They show how bouncy it is. Double yellow dot balls, the least bouncy, are used by top players."],["Why do players wear goggles?","Juniors and doubles players must wear eye protection. The ball and racket move fast in a small space."]],
  words:[["The T","The center of the court."],["Boast","A shot off a side wall that then hits the front wall."],["Drop shot","A soft shot that dies at the front."],["Drive","A hard shot down the side wall."],["Let","A replayed rally."],["Stroke","A point awarded for interference."],["Tin","The board at the bottom of the front wall."],["Nick","Where the wall meets the floor. A ball hitting it rolls flat and is unplayable."]],
  quiz:[{q:"How many points win a game?",o:["9","11","15","21"],a:1,why:"Eleven, win by 2."},{q:"What happens if the ball hits the tin?",o:["Replay","The hitter loses the rally","A let","Nothing"],a:1,why:"It's down."},{q:"How many bounces are allowed before you return it?",o:["0","1","2","3"],a:1,why:"One."},{q:"What's a stroke?",o:["A replay","A point awarded for interference","A type of serve","A foul by the referee"],a:1,why:"A point to the obstructed player."},{q:"What's a let?",o:["A point","A replayed rally","A penalty","A timeout"],a:1,why:"The rally is replayed."},{q:"Where must the serve hit the front wall?",o:["Anywhere","Between the service line and the out line","Below the tin","On the side wall"],a:1,why:"Between those lines."},{q:"Can the ball hit the side walls?",o:["Yes","No"],a:0,why:"Yes, as long as it reaches the front wall before the second bounce."},{q:"Why do players return to the T?",o:["It's required","To reach every corner quickly","To rest","To serve"],a:1,why:"It's the best position."},{q:"Who scores in point-a-rally scoring?",o:["Only the server","Whoever wins the rally","Only the receiver","Nobody until game point"],a:1,why:"The rally winner."},{q:"How many games in a top-level match?",o:["Best of 3","Best of 5","Best of 7","One"],a:1,why:"Best of five."}],
  footer:"Rules on this page follow World Squash singles rules with point-a-rally scoring to 11."})};
})();
